"""Initial revision

Revision ID: 49c9b4312220
Revises:
Create Date: 2024-12-19 18:35:45.285758

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "49c9b4312220"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
