"""Create sqlalchemy models

Revision ID: ffc2c31632b9
Revises: 49c9b4312220
Create Date: 2024-12-20 14:18:50.379891

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ffc2c31632b9"
down_revision: Union[str, None] = "49c9b4312220"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
