"""add last sent link field to SiteFilter table

Revision ID: 6c0736cb2fb4
Revises: f656fa5d0f70
Create Date: 2025-03-09 09:41:54.666306

"""

from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c0736cb2fb4"
down_revision: Union[str, None] = "f656fa5d0f70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sites_filters", sa.Column("last_sent_link", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sites_filters", "last_sent_link")
    # ### end Alembic commands ###
