"""init tables

Revision ID: c11e9b808883
Revises:
Create Date: 2024-12-23 12:00:59.136059

"""

from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c11e9b808883"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sites",
        sa.Column("site_name", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("site_name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "filters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=32), nullable=False),
        sa.Column(
            "experience",
            sa.Enum(
                "less_than_1_year",
                "one_to_three_years",
                "three_to_five_years",
                "more_than_5_years",
                name="experienceenum",
            ),
            nullable=False,
        ),
        sa.Column("abroad", sa.BOOLEAN(), nullable=False),
        sa.Column("only_remote", sa.BOOLEAN(), nullable=False),
        sa.Column("active", sa.BOOLEAN(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sites_filters",
        sa.Column("site_name", sa.String(length=32), nullable=False),
        sa.Column("filter_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["filter_id"], ["filters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["site_name"], ["sites.site_name"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("site_name", "filter_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sites_filters")
    op.drop_table("filters")
    op.drop_table("users")
    op.drop_table("sites")
    # ### end Alembic commands ###
