"""delete abroad field from Filter

Revision ID: f656fa5d0f70
Revises: c11e9b808883
Create Date: 2024-12-29 11:57:10.338565

"""

from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f656fa5d0f70"
down_revision: Union[str, None] = "c11e9b808883"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("filters", "abroad")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("filters", sa.Column("abroad", sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
